### ISSUE TITLE
XSD invalid namespace reference

### ISSUE THREAD

**Issue by dlmiles** [DK-Hostmaster/epp-xsd-files#20]
https://github.com/DK-Hostmaster/epp-xsd-files/blob/master/dkhm-4.0.xsd#L17

This erroneously references the prefix "urn:ietf:" when it should be "urn:dkhm:" to make the result "urn:dkhm:params:xml:ns:dkhm-domain-4.0"

This error seems to be repeated for 4.1 as well:

https://github.com/DK-Hostmaster/epp-xsd-files/blob/master/dkhm-4.1.xsd#L17

This ignores the matter that neither the (dkhm-domain-4.0 or domain-1.0) namespace contents are referenced from inside the XSD directly, so the IMPORT element should be omitted entirely as a better solution, along with any unused namespace prefixes.

**Comment by jonasbn** [comment]
Thanks @dlmiles 

Looks like a copy-paste error on my behalf, I will address is ASAP
